FROM ghcr.io/rhadp/builder:latest

USER root

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install "git+https://github.com/jumpstarter-dev/jumpstarter#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# init scripts
COPY init-git ${INIT_SCRIPTS_DIR}/init-git

RUN mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chmod +x ${INIT_SCRIPTS_DIR}/*

# create symbolic links from /home/workspace/ -> /home/user/
RUN stow . -t /home/user/ -d /home/workspace/ --no-folding

# set permissions on the user's home directory
RUN chown -R 10001:0 /home/workspace /home/user && \
    chmod -R g=u /home/user /home/workspace

USER 10001