FROM ghcr.io/rhadp/builder:latest

USER root

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install "git+https://github.com/rhadp/jumpstarter@develop#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# init scripts, create directories, and set permissions in a single layer
COPY init-git ${INIT_SCRIPTS_DIR}/init-git

RUN mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chmod +x ${INIT_SCRIPTS_DIR}/* && \
    stow . -t /home/user/ -d /home/workspace/ --no-folding && \
    chown -R 10001:0 /home/workspace /home/user && \
    chmod -R g=u /home/user /home/workspace

USER 10001