FROM ghcr.io/rhadp/runtime:latest

ARG TARGETARCH
USER root

# install additional python dependencies and set permissions in a single layer
COPY requirements.txt /tmp/requirements.txt
COPY s3-upload.py /home/user/s3-upload.py

RUN uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt && \
    chgrp -R 0 /home/user && chmod -R g=u /home/user

USER 10001
