FROM ghcr.io/rhadp/base:latest

USER root

# $PROFILE_EXT contains all additions made to the bash environment
ENV PROFILE_EXT=/etc/profile.d/udi_environment.sh
RUN touch ${PROFILE_EXT} && chown 10001 ${PROFILE_EXT}

# misc development packages and stuff
RUN dnf install -y --setopt=tsflags=nodocs \
    autoconf patch lsof redhat-rpm-config \
    openssl-devel libcurl-devel libxml2-devel libxslt-devel zlib-devel \
    unzip wget bzip2 zip \
    podman

# c/c++ and stuff
RUN dnf install -y --setopt=tsflags=nodocs \ 
    llvm-toolset \
    gcc gcc-c++ clang clang-libs clang-tools-extra \
    gdb cmake automake autoconf make

# rust
ENV CARGO_HOME=/home/workspace/.cargo \
    RUSTUP_HOME=/home/workspace/.rustup \
    PATH=/home/workspace/.cargo/bin:${PATH}

RUN mkdir -p /home/workspace/.cargo && \
    mkdir -p /home/workspace/.rustup && \
    curl --proto '=https' --tlsv1.2 -sSfo rustup https://sh.rustup.rs && \
    chmod +x rustup && \
    mv rustup /usr/bin/ && \
    rustup -y --no-modify-path --profile minimal -c rust-src -c rust-analysis -c rls && \
    chgrp -R 0 /home/workspace && chmod -R g=u /home/workspace

# alias docker to podman
RUN echo 'alias docker=podman' >> ${PROFILE_EXT}

# configure container engine
COPY --chown=0:0 containers.conf /etc/containers/containers.conf

# create symbolic links from /home/workspace/ -> /home/user/
RUN stow . -t /home/user/ -d /home/workspace/ --no-folding

# set permissions on the user's home directory
RUN chgrp -R 0 /home/user && chmod -R g=u /home/user

USER 10001
