# this is a modified version of https://github.com/devfile/cloud-dev-images/blob/main/ubi9/Dockerfile

FROM registry.access.redhat.com/ubi9/ubi:9.7 
# latest is: -1764163501

ARG TARGETARCH
USER root

RUN dnf install -y --setopt=tsflags=nodocs \
    python3.12 \
    python3.12-devel \
    python3-pip \
    nss_wrapper \
    golang-oras \
    kmod \
    openssh-clients \
    nc \
    jq yq \
    git && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# create default directories
RUN mkdir -p /home/user/.config/pip && \
    mkdir -p /home/user/.config/containers && \
    mkdir -p /home/user/.cache && \
    mkdir -p /home/workspace/.scripts/init && \
    mkdir -p /home/user/.ssh

# oc client
ENV OC_VERSION=4.20
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        curl -L https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    else \
        curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    fi | tar -C /usr/local/bin -xz --no-same-owner && \
    chmod +x /usr/local/bin/oc

    # python dependencies
COPY --from=ghcr.io/astral-sh/uv:latest /uv  /bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /bin/uvx

# set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.12 VIRTUAL_ENV=/venv

# install python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv venv /venv && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# This will make sure that we always run python from our venv instead
RUN echo "alias python='uv run python'" >> /home/user/.bashrc
ENV PATH="/venv/bin:$PATH"

# add init-workspace script
ENV SCRIPTS_DIR=/home/workspace/.scripts \
    INIT_SCRIPTS_DIR=/home/workspace/.scripts/init

COPY init-workspace ${SCRIPTS_DIR}/init-workspace
RUN chmod +x ${SCRIPTS_DIR}/init-workspace

# create symbolic links from /home/workspace/ -> /home/user/
RUN stow . -t /home/user/ -d /home/workspace/ --no-folding

# set permissions on /etc/passwd, /etc/group, /etc/pki and /home to allow arbitrary users to write
RUN chgrp -R 0 /home && chmod -R g=u /etc/passwd /etc/group /home /etc/pki

# set permissions on the user's home directory
RUN chgrp -R 0 /home && chmod -R g=u /home

# Set SHELL to configure the default shell used in web terminals
# https://github.com/eclipse/che/issues/22524
ENV SHELL=/usr/bin/bash

# cleanup dnf cache
RUN dnf -y clean all --enablerepo='*'

# Set HOME. Required for CRI-o to set /etc/passwd correctly and in general for other CLI tools
ENV HOME=/home/user

CMD ["tail", "-f", "/dev/null"]