FROM ghcr.io/rhadp/base:latest

ARG TARGETARCH
USER root

RUN dnf install -y --setopt=tsflags=nodocs \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    if [ "$TARGETARCH" = "arm64" ]; then \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-stream-repos-9.0-26.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-gpg-keys-9.0-26.el9.noarch.rpm; \
    else \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-9.0-26.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-9.0-26.el9.noarch.rpm; \
    fi && \
    dnf install -y --setopt=tsflags=nodocs \
    python3-libgpiod \
    qemu-kvm qemu-img \
    && dnf -y clean all --enablerepo='*' \
    && rm -rf /var/cache/dnf

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv venv /venv && \
    uv pip install "git+https://github.com/jumpstarter-dev/jumpstarter#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# create directories and set permissions
RUN mkdir -p /etc/jumpstarter/exporters && \ 
    mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chgrp -R 0 /home/user && chmod -R g=u /home/user

USER 10001
