FROM ghcr.io/rhadp/base:latest

ARG TARGETARCH
USER root

# install virtualization packages
RUN dnf install -y --setopt=tsflags=nodocs \
    python3-libgpiod nss_wrapper \
    qemu-kvm qemu-img libvirt \
    "@virtualization-hypervisor" "@virtualization-client" "@virtualization-platform" "@virtualization-tools" \
    virt-install virt-viewer \
    genisoimage \
    && dnf -y clean all --enablerepo='*' \
    && rm -rf /var/cache/dnf

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install "git+https://github.com/rhadp/jumpstarter@develop#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# create directories and set permissions
RUN mkdir -p /etc/jumpstarter/exporters && \ 
    mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chgrp -R 0 /home/user && chmod -R g=u /home/user

USER 10001
